### ISSUE TITLE
After install, internal 500 error when loading pages

### ISSUE THREAD

**Issue by clintbellanger** [techlib/celus#18]
We got through the basic install instructions for celus. Also, we're not using Shibboleth so we also completed the suggested instructions in issue #10 

In browser, the outline of the celus dashboard starts loading but we get these 500 errors

<pre>
api/user/:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api/organization/:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
</pre>

In /var/log/httpd/error_log we see these details:

> mod_wsgi (pid=3884): Failed to exec Python script file '/opt/celus/config/wsgi.py'.
> mod_wsgi (pid=3884): Exception occurred processing WSGI script '/opt/celus/config/wsgi.py'.
> Traceback (most recent call last):
>   File "/opt/virtualenvs/celus/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
>     self.connect()
>   File "/opt/virtualenvs/celus/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
>     self.connection = self.get_new_connection(conn_params)
>   File "/opt/virtualenvs/celus/lib/python3.6/site-packages/django_prometheus/db/common.py", line 44, in get_new_connection
>     return super(DatabaseWrapperMixin, self).get_new_connection(*args, **kwargs)
>   File "/opt/virtualenvs/celus/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
>     connection = Database.connect(**conn_params)
>   File "/opt/virtualenvs/celus/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
>     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> psycopg2.OperationalError: could not connect to server: Permission denied
> \tIs the server running on host "127.0.0.1" and accepting
> \tTCP/IP connections on port 5432?

Is there something we're missing with port 5432? Thanks!

**Comment by clintbellanger** [comment]
We discovered that SELinux was causing this issue. For anyone else having this issue, we stopped postgresql and httpd and ran this command:

> setsebool -P httpd_can_network_connect 1

Then restarted those services, and that error is now clear.
